### ISSUE TITLE
JupyterLab widgets fail to render if user tries to install compute explicitly 

### ISSUE THREAD

**Issue by mitkotak** [cybergis/job-supervisor-python-sdk#47]
## Problem

The UI breaks If the user tries to install cybergis-compute-python-sdk on top of the version that's already provided.
```jupyterlab
import sys
!{sys.executable} -m pip install --ignore-installed git+https://github.com/cybergis/cybergis-compute-python-sdk.git
```
<img width="1106" alt="Screen Shot 2022-09-01 at 10 22 47 AM" src="https://user-images.githubusercontent.com/53411468/187951754-aefc81f7-4ac0-4298-b036-a94e06d71645.png">

<img width="1087" alt="Screen Shot 2022-09-01 at 10 20 07 AM" src="https://user-images.githubusercontent.com/53411468/187951148-5f2c16fc-10b3-4daf-9522-afc149679508.png">

This is happening due to dependency conflicts as seen in the output for the pip command

<img width="1106" alt="Screen Shot 2022-09-01 at 10 20 56 AM" src="https://user-images.githubusercontent.com/53411468/187951323-86648995-669d-40fd-9aea-b9447fc0c99e.png">

## Proposed Solution

Ask users to restart their container and avoid installing the cybergis-compute-python-sdk explicitly.

**Comment by alexandermichels** [comment]
It's hard to tell exactly what causes this problem. It could be:

* reinstalling dependencies (jupyter, ipywidgets, etc.)  cause conflicts between themselves.
* reinstalling those dependencies clash with the Jupyter environment you're running in
* reinstalling those dependencies create issues within our code

I recommend using the following to install from now on so as to not install new versions of the dependencies:

```
pip install --force-reinstall --no-deps git+https://github.com/cybergis/cybergis-compute-python-sdk.git
```

As you noted, for users on CyberGISX, we recommend restarting your container by going to "File" -> "Hub Control Panel" -> "Stop My Server". Once it stops, restart it. This works because we have configured pip to install packages into non-persistent storage by default. 

Also note that the Python 0.9.0  kernel has our SDK installed by default, so this pip install is only necessary if you need a particular version of the code.

Thank you for documenting this problem. Since we have a couple of solutions that work to resolve the problem (restart container and use the flags mentioned above), I'm going to close it for now.
